### ISSUE TITLE
How to set properties without plist?

### ISSUE THREAD

**Issue by zdnk** [exponea/exponea-ios-sdk#10]
I didnt find any way to set `automaticPushNotificationTracking` to false without a plist which is not safe as anyone can pull it out from the packaged *.ipa and read our tokens and it also makes it more complex to have multiple environments.

What would you recommend? Could you extend the code-based configuration capabilities?

**Comment by Igi4** [comment]
Hey @zdnk , that's a good point, thanks :)

We will add a new method, e.g. `Exponea.configure(configuration: Configuration)`  which will allow the users to use all the configuration options as with the plist file. This will let you also configure `automaticPushNotificationTracking` as well as manage multiple environments as you can configure Exponea object in the code with the full config options.

If everything goes well, it should be part of the next upcoming release next week :)

**Comment by zdnk** [comment]
I was hoping you would do exactly that :)
I would suggest method signature of `Exponea.configure(with: Configuration)` to follow Swift naming conventions.

**Comment by zdnk** [comment]
> If everything goes well, it should be part of the next upcoming release next week :)

Would it be possible to release the fix this week? Unfortunately we are scheduled to put the final build for testing by Wednesday :(

**Comment by Igi4** [comment]
Hey @zdnk, I'm sorry but we already prioritized this on top of other things and unfortunately the best we can do is next week.

**Comment by Igi4** [comment]
Hey @zdnk, new release has been done and there is a new way to configure the SDK from the code, there is more info about it here https://github.com/exponea/exponea-ios-sdk/blob/develop/Documentation/CONFIG.md :)

Please let me know if you have any more questions.

**Comment by zdnk** [comment]
Cool thanks :)
