### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by zdnk** [exponea/exponea-ios-sdk#11]
Hello, do you have any plans to support Swift Package Manager?

**Comment by Igi4** [comment]
@zdnk We haven't so far but would you prefer it to Cocoapods or Carthage? Based on a very quick analysis it should be pretty straightforward implementation so we could consider it if people would like to use it :)

**Comment by zdnk** [comment]
Since SPM is now supported natively by Xcode I would prefer it as we already have most of our dependencies resolved by SPM :)

**Comment by Igi4** [comment]
Thanks for the info :) I have added it to our internal backlog and we will integrate it in the future.

**Comment by sjavora** [comment]
@Igi4 hey, any progress on this? We'd also like to switch to SPM wherever possible.

**Comment by wassil** [comment]
Hi, we've already done some exploration here and it's not as straight-forward as we hoped, but it seems doable. We already support cocoapods and carthage which doesn't make this any easier. Currently our pipeline is full for ~ next 2 months, so it might take a while, but we are interested in supporting spm in the future

**Comment by adameen** [comment]
Bump. Hi :) any updates about SPM support? We would also appreciate it.

**Comment by michaela-dev** [comment]
Hi guys, we added SPM support in the 2.11.0 release. Thanks for the patience :)

**Comment by username0x0a** [comment]
@michaela-dev

It still needs some minor polishing 👀 this has to be handled in the `Package.swift` file mostly.

![Screenshot 2021-06-04 at 15 41 39](https://user-images.githubusercontent.com/5228484/120811333-27273780-c54c-11eb-859c-6cbfab773e10.png)

Looking forward to seeing a quickfix. 🙌

**Comment by michaela-dev** [comment]
@username0x0a On version 2.11.1 warnings are no longer appearing, hence closing the issue. If you are still facing this, please create a new one regarding warnings. Thanks

**Comment by username0x0a** [comment]
Added a [follow-up issue](https://github.com/exponea/exponea-ios-sdk/issues/35). 👍
