### ISSUE TITLE
Manual install

### ISSUE THREAD

**Issue by fixique** [exponea/exponea-ios-sdk#12]
Hello, do you have some guide for manual sdk installing? 
Is it possible?

**Comment by wassil** [comment]
Hi,
there is no guide, but it is possible. If you clone the sdk sources, you can see it contains Example project that's setup without pods, you can do the same.
Clone the sdk repo, create workspace and have your app and exponea sdk projects in the same workspace - just like the workspace that's in the repo.
Then setup frameworks for your app to include exponeaSDK framework(and if you want to use rich notifications also notification framework)
Should look something like this:
![Screenshot 2020-01-15 at 14 01 09](https://user-images.githubusercontent.com/1576241/72436032-c99c1a80-379f-11ea-8d43-e19e313cf795.png)

Just so I understand your use-case better, why do need to install the SDK manually? 
I think you're better off using Pods/Carthage, updating to latest version is much easier.

**Comment by fixique** [comment]
@wassil Thank you for fast reply! 
I am at the design stage of my product and we are using modular architecture. Maybe you are right and we will use pod dependency of your sdk. 

I will reply later when we finally integrate your sdk)

**Comment by fixique** [comment]
You were right. I used integration with cocoapods. There is no issues with that installation way. I was worried because Firebase has crash when I install by cocoapods in modular architecture.
Thank you for your help!
