### ISSUE TITLE
DatabaseManager waits on main queue

### ISSUE THREAD

**Issue by sjavora** [exponea/exponea-ios-sdk#15]
Just noticed this when profiling our app - [DatabaseManager.swift](https://github.com/exponea/exponea-ios-sdk/blob/develop/ExponeaSDK/ExponeaSDK/Classes/Database/DatabaseManager.swift) uses the [context](https://github.com/exponea/exponea-ios-sdk/blob/58c4ca0fad725764cec34af336b5266be99f4a15/ExponeaSDK/ExponeaSDK/Classes/Database/DatabaseManager.swift#L19) property for interacting with Core Data. This is defined as `persistentContainer.viewContext`. This means that `context` is associated with the main queue as described in [the docs](https://developer.apple.com/documentation/coredata/nspersistentcontainer/1640622-viewcontext). All operations in `DatabaseManager` begin with `context.performAndWait` - `perform` and `performAndWait` run the block on the queue that the context is associated with... in this case, the main queue.

Since `performAndWait` [is run synchronously on the context's queue](https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext/1506364-performandwait), **the main queue is blocked** while `DatabaseManager` methods are run. This results in our app freezing when the database manager decides to do something.

As far as I know, there is nothing the app can do about this. Please let me know if my analysis is wrong, but I can't find anything else in the time profiler to explain this.

**Comment by wassil** [comment]
Yup, that makes sense. The SDK had issues with thread safety so switching to background thread seemed a bit crazy, but those issues were fixed a couple of versions back and this slipped. 
I'll add it to our backlog, with current state it should be an easy fix.

Thanks for the report!

**Comment by wassil** [comment]
Just released version 2.8.0 where `DatabaseManager` uses background context.
This should be resolved, thanks again for reporting!
