### ISSUE TITLE
UIApplication.shared.registerForRemoteNotifications() is called on a background thread

### ISSUE THREAD

**Issue by sgrgrsn** [exponea/exponea-ios-sdk#16]
The Main Thread Checker is complaining about the `UIApplication.shared.registerForRemoteNotifications()` is being called from a background thread. According to the stack trace I can see it's being called from the callback after checking if the UNNotificationCenter is authorized (`UNAuthorizationStatusProvider.current.isAuthorized`).

I found [this piece in the `PushNotificationManager`](https://github.com/exponea/exponea-ios-sdk/blob/develop/ExponeaSDK/ExponeaSDK/Classes/Push%20Notifications/PushNotificationManager.swift#L74) where you call the `UIApplication.shared.registerForRemoteNotifications()` in the completion handler. This is not guaranteed to be called on the Main Thread so it should be wrapped in a `DispatchQueue.main.async {}` or similar.

From Xcode:
![CleanShot 2020-07-22 at 12 57 35](https://user-images.githubusercontent.com/6108577/88168665-064b4180-cc1b-11ea-87c2-4082b570d5fb.png)

**Comment by wassil** [comment]
That makes sense, added to our backlog

**Comment by wassil** [comment]
Issue has been fixed as part of our 2.8.0 release.

Thanks again for reporting!
