### ISSUE TITLE
Uploading data to Visual Studio App Center failed

### ISSUE THREAD

**Issue by sgrgrsn** [exponea/exponea-ios-sdk#17]
Hi there 👋 

I'm currently setting up ExponeaSDK in an app and I get this error in my logging output from time to time. I don't have specific steps to reproduce it but I'm pretty sure it happens as a part of the app launch.

```
2020-07-22 01:19:36550 ExponeaSDK ❗️ ERROR [VSAppCenterTelemetryUpload.swift]:104 upload(data:completionHandler:): Uploading data to Visual Studio App Center failed.

Error: Optional(Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9816, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x28334a9a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://in.appcenter.ms/logs?Api-Version=1.0.0, NSErrorFailingURLStringKey=https://in.appcenter.ms/logs?Api-Version=1.0.0, _kCFStreamErrorDomainKey=3})
```

Why do I get this error and why does the SDK attempt to share data with Microsoft?

I couldn't find anything in the documentation mentioning this.

It would be really nice if you could provide some more details about this.

Thanks.

**Comment by wassil** [comment]
Hi,
We'll take look at the error.
What you're seeing is our internal telemetry. 
We measure number of installations/sessions and upload crash stack traces originating in the SDK to Visual Studio App Center.

**Comment by sgrgrsn** [comment]
Thanks for the reply.

Are there any options for disabling this? We don't want to change our user consent to include details about sharing data with Microsoft.

**Comment by adam1929** [comment]
Hi @sgrgrsn as Wassil mentioned, these data are analytics of SDK usage. They definitely did not contain any personal data. Anyway, answer on your question: sending of these data cannot be turned off.
