### ISSUE TITLE
Push Token not setting in Exponea but SDK is sending it

### ISSUE THREAD

**Issue by jackjpark** [exponea/exponea-ios-sdk#19]
Hi, 

Im moving from the automatic swizzling handling of notifications to the new method using ExponeaAppDelegate

In the logging i see:

`2020-09-10 05:23:29374 ExponeaSDK ℹ️ VERBOSE [TrackingManager.swift]:184 track(_:with:): Tracking event of type: registerPushToken with params [ExponeaSDK.DataType.pushNotificationToken(token: Optional("TOKENSTRING"), authorized: true)]`

However in exponea the userID has no token. Please can you advise what could be wrong here, I dont see any errors...

All other tracking and events are visible in exponea, its just not adding the push token...

**Comment by wassil** [comment]
Hi,
the log that you pasted in your question is produced when tracking of the event starts. 
Next, we pick a project token(if you're using projectMapping, I'd check that). 
Event with project token is then written into internal database of the application. 
Last step is flushing the event to Exponea servers. If you're using `.immediate` flushMode, flushing should happen right after the event is tracked. This is what you should see in the logs:
```
2020-09-11 09:38:26489 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:81 prepareRequest(parameters:customerIds:): Created request: 
[Request]
POST https://cloud-api.exponea.com/track/v2/projects/f3a64f78-c27c-11e9-8a72-f69eea2c8d5c/customers
Content-Type: application/json
Accept: application/json
Authorization: REDACTED
HTTP Body:
{
  "customer_ids" : {
    "cookie" : "BE8F530F-34D4-435A-AA85-CA989F3AC09E"
  },
  "properties" : {
    "apple_push_notification_id" : "REDACTED MY REAL TOKEN",
    "apple_push_notification_authorized" : true
  },
  "timestamp" : 1599809903.2902641
}

2020-09-11 09:38:27380 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:145 process(_:data:error:resultAction:): Response received:
[Response]
HTTP 200 https://cloud-api.exponea.com/track/v2/projects/f3a64f78-c27c-11e9-8a72-f69eea2c8d5c/customers/events
Date: Fri, 11 Sep 2020 07:38:26 GMT
access-control-allow-credentials: true
Via: 1.1 google
Content-Type: application/json
Access-Control-Allow-Origin: *
x-request-id: 02a2c841-5d98-4c74-bb87-df4dcfc8d8e0
alt-svc: clear
Content-Length: 29
Response Body:
{"success":true,"errors":[]}
```
Request contains `apple_push_notification_id` which is the name of customer property that holds push token.
Check that response is successful, and that request was created at all. If not, I'd double check flushMode setting.
If you can see the request and response is successful, the issue might be on the server.

**Comment by jackjpark** [comment]
> Hi,
> the log that you pasted in your question is produced when tracking of the event starts.
> Next, we pick a project token(if you're using projectMapping, I'd check that).
> Event with project token is then written into internal database of the application.
> Last step is flushing the event to Exponea servers. If you're using `.immediate` flushMode, flushing should happen right after the event is tracked. This is what you should see in the logs:
> 
> ```
> 2020-09-11 09:38:26489 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:81 prepareRequest(parameters:customerIds:): Created request: 
> [Request]
> POST https://cloud-api.exponea.com/track/v2/projects/f3a64f78-c27c-11e9-8a72-f69eea2c8d5c/customers
> Content-Type: application/json
> Accept: application/json
> Authorization: REDACTED
> HTTP Body:
> {
>   "customer_ids" : {
>     "cookie" : "BE8F530F-34D4-435A-AA85-CA989F3AC09E"
>   },
>   "properties" : {
>     "apple_push_notification_id" : "REDACTED MY REAL TOKEN",
>     "apple_push_notification_authorized" : true
>   },
>   "timestamp" : 1599809903.2902641
> }
> 
> 2020-09-11 09:38:27380 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:145 process(_:data:error:resultAction:): Response received:
> [Response]
> HTTP 200 https://cloud-api.exponea.com/track/v2/projects/f3a64f78-c27c-11e9-8a72-f69eea2c8d5c/customers/events
> Date: Fri, 11 Sep 2020 07:38:26 GMT
> access-control-allow-credentials: true
> Via: 1.1 google
> Content-Type: application/json
> Access-Control-Allow-Origin: *
> x-request-id: 02a2c841-5d98-4c74-bb87-df4dcfc8d8e0
> alt-svc: clear
> Content-Length: 29
> Response Body:
> {"success":true,"errors":[]}
> ```
> 
> Request contains `apple_push_notification_id` which is the name of customer property that holds push token.
> Check that response is successful, and that request was created at all. If not, I'd double check flushMode setting.
> If you can see the request and response is successful, the issue might be on the server.

Hi, whats project mapping sorry? Im following your github recommended implimentation

Here is a full log aster the initial line I sent

`2020-09-11 09:13:11468 ExponeaSDK ℹ️ VERBOSE [TrackingManager.swift]:184 track(_:with:): Tracking event of type: registerPushToken with params [ExponeaSDK.DataType.pushNotificationToken(token: Optional("TOKENSTRINGHERE"), authorized: true)]
2020-09-11 09:13:11893 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:145 process(_:data:error:resultAction:): Response received:
2020-09-11 09:13:11893 ExponeaSDK ℹ️ VERBOSE [FlushingManager.swift]:172 onObjectFlush(flushableObject:result:): Successfully uploaded tracking object: 0xb3008d79a0aa50dc <x-coredata://3AB37FF3-9011-43AE-A6F7-7C3DC28A3EF5/TrackEvent/p9>.
2020-09-11 09:13:11923 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:145 process(_:data:error:resultAction:): Response received:
2020-09-11 09:13:11924 ExponeaSDK ℹ️ VERBOSE [FlushingManager.swift]:172 onObjectFlush(flushableObject:result:): Successfully uploaded tracking object: 0xb3008d79a0a650dc <x-coredata://3AB37FF3-9011-43AE-A6F7-7C3DC28A3EF5/TrackEvent/p10>.
2020-09-11 09:13:12068 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:145 process(_:data:error:resultAction:): Response received:
2020-09-11 09:13:12068 ExponeaSDK ℹ️ VERBOSE [FlushingManager.swift]:172 onObjectFlush(flushableObject:result:): Successfully uploaded tracking object: 0xb3008d79a09a50de <x-coredata://3AB37FF3-9011-43AE-A6F7-7C3DC28A3EF5/TrackCustomer/p5>.
2020-09-11 09:13:12277 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:81 prepareRequest(parameters:customerIds:): Created request: 
2020-09-11 09:13:12388 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:145 process(_:data:error:resultAction:): Response received:
2020-09-11 09:13:14495 ExponeaSDK ℹ️ VERBOSE [FlushingManager.swift]:112 flushData(completion:): Flushing data: 1 total objects to upload, 0 events and 1 customer updates.
2020-09-11 09:13:14496 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:81 prepareRequest(parameters:customerIds:): Created request: 
2020-09-11 09:13:14571 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:145 process(_:data:error:resultAction:): Response received:
2020-09-11 09:13:14571 ExponeaSDK ℹ️ VERBOSE [FlushingManager.swift]:172 onObjectFlush(flushableObject:result:): Successfully uploaded tracking object: 0xb3008d79a09650de <x-coredata://3AB37FF3-9011-43AE-A6F7-7C3DC28A3EF5/TrackCustomer/p6>.
2020-09-11 09:13:14590 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:81 prepareRequest(parameters:customerIds:): Created request: 
2020-09-11 09:13:14675 ExponeaSDK ℹ️ VERBOSE [RequestFactory.swift]:145 process(_:data:error:resultAction:): Response received:
`

My Config is as so

`        Exponea.shared.configure(
            Exponea.ProjectSettings(
                projectToken: "PROJTOKEN",
                authorization: .token("AUTHTOKEN")
            ),
            pushNotificationTracking: .enabled(appGroup: "APPGROUP"),
            flushingSetup: Exponea.FlushingSetup(mode: .immediate)
        )`

**Comment by wassil** [comment]
I think you have to configure your access token on Exponea backend. 
In the version you're migrating to we added a customer property `apple_push_notification_authorized ` and your token is most probably not able to create it - that's why you're getting "not authorized to update specified customer properties" 

Go to Project Settings/API and look at "API groups". Select the group that you're using in your app(most probably it's default). Then check the "Group permissions" below that. You should allow the token to either create new customer properties, or create the property `apple_push_notification_authorized` and allow the token to write into it.

**Comment by jackjpark** [comment]
> I think you have to configure your access token on Exponea backend.
> In the version you're migrating to we added a customer property `apple_push_notification_authorized ` and your token is most probably not able to create it - that's why you're getting "not authorized to update specified customer properties"
> 
> Go to Project Settings/API and look at "API groups". Select the group that you're using in your app(most probably it's default). Then check the "Group permissions" below that. You should allow the token to either create new customer properties, or create the property `apple_push_notification_authorized` and allow the token to write into it.

yep this seems to havbe fixed it, i had to allow the API group to create properties. THis should really be documented very clearly in a migration guide as I dont see where i could have found this info without creating an issue, thanks

**Comment by jackjpark** [comment]
yeah to add to the above, the push notification ID in exponea is not the users push token as printed in app, its being changed in some way? Could this be why exponea/apns says its a bad device token

**Comment by wassil** [comment]
It shouldn't be changed in any way. I'd try to do a fresh install of the application.
How are the tokens different?
Btw. bad device token may also be result of incorrect bundle id or incorrect certificate(production vs. develoment)

**Comment by jackjpark** [comment]
> It shouldn't be changed in any way. I'd try to do a fresh install of the application.
> How are the tokens different?
> Btw. bad device token may also be result of incorrect bundle id or incorrect certificate(production vs. develoment)

Ive sorted it now, seems tokens on the dev scheme just dont work, but on staging build they did so it seems to all be good now

**Comment by wassil** [comment]
They do work, buy you'd have to use a different(development) certificate for APNS

**Comment by jackjpark** [comment]
@wassil thanks, ouyt of interest, i see that your new setup requires me to hand off to exponea in 

```
userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void)
```

i already have custom deeplink handling in this fucntion, causing things like exponea URL notifications to open 2 webviews.

Is there a way i can work out if a push was send from exponea in the code so i can if/else on which handler to execute, exponea or native?

**Comment by wassil** [comment]
What do you mean by "it'll execute twice"? Which Exponea function is called twice?
Do you use another SDKs to handle push notifications?
