### ISSUE TITLE
Xcode 12 warnings, NSSecureCoding

### ISSUE THREAD

**Issue by anonymcek** [exponea/exponea-ios-sdk#21]
Xcode 12 shows buildtime warnings about some core data attributes usinf insecure value transformer.

`Customer.uuid is using a nil or insecure value transformer. Please switch to NSSecureUnarchiveFromDataTransformerName or a custom NSValueTransformer subclass of NSSecureUnarchiveFromDataTransformer`
and
`KeyValueItem.value is using a nil or insecure value transformer. Please switch to NSSecureUnarchiveFromDataTransformerName or a custom NSValueTransformer subclass of NSSecureUnarchiveFromDataTransformer`

Are you planning to fix this issue in near future?

**Comment by wassil** [comment]
Hi, I'm looking at it right now. 
There are multiple problems after Xcode 12 update, mainly tests won't even compile.
We'll release a new version for Xcode 12

**Comment by wassil** [comment]
Fixed in 2.9.2
