### ISSUE TITLE
Xcode 12 documentation

### ISSUE THREAD

**Issue by sadiq81** [exponea/exponea-ios-sdk#23]
It would be a good idea to update your readme so that I don't have to spend time looking for the reason behind commit d0b946a0e016f2aeaf88a19157921e1ff2d580fd

**Comment by wassil** [comment]
I'm not sure what you mean. Update documentation with instructions on how to use carthage?

**Comment by sadiq81** [comment]
In you Readme you write 

> Open Cartfile file located in your project folder
> Add ExponeaSDK dependency
> github "exponea/exponea-ios-sdk
> Run the Carthage update command
> carthage update exponea-ios-sdk

But when in fact when using Xcode 12 one should use the shell script.
