### ISSUE TITLE
Base URL config

### ISSUE THREAD

**Issue by MatejBordac** [exponea/exponea-ios-sdk#24]
Configuration of base URL requires not having "/" at the end. E.g.:
https://api.exponea.com <- works
https://api.exponea.com/ <- doesn't work

My assumption is, that simple string concatenation is done (as in BASE_URL + API_PATH), instead of proper URL path joining.

**Comment by wassil** [comment]
Makes sense, added to our backlog.
Thank you!

**Comment by michaela-dev** [comment]
Hi @MatejBordac, this should be already fixed in 2.11.0 release.

**Comment by MatejBordac** [comment]
Already fixed
