### ISSUE TITLE
Objective C support

### ISSUE THREAD

**Issue by phaneendrakv** [exponea/exponea-ios-sdk#26]
Has anyone tried integrating with the Objective C project? I need some info or guidelines to make the SDK work with the Objective C project.

**Comment by username0x0a** [comment]
Not an optimal solution but I'm trying to maintain [an Objective-C port](https://github.com/username0x0a/exponea-objc-sdk) with most of the stuff covered. 💡

**Comment by adam1929** [comment]
@username0x0a thanks for tip, but your link is not working (404). Are you able to update it?
@phaneendrakv We have no ObjectiveC "proxy" upon ExponeaType.swift class and I'm not able to tell if it can be fully achieved. I will keep with answer from @username0x0a or with some similar approach.
