### ISSUE TITLE
Blocking calls on main thread

### ISSUE THREAD

**Issue by mrublev** [exponea/exponea-ios-sdk#27]
Hi,

There is an issue #15 which is closed, but from what I see the problem still exists.
I'm using latest version of SDK 2.11.0. And there are some calls being made by Exponea which make UI not responsive for small periods right after app launch. Attaching screenshot with a stack trace.

<img src="https://user-images.githubusercontent.com/1237778/116008022-723c5980-a634-11eb-8823-b719a3f3e9a8.png" width="250" />

Is there a way to reduce that influence on the main thread at least at startup?

**Comment by Igi4** [comment]
Hi @mrublev, sorry for later reply. We'll take a look at this more thoroughly and I'll let you know if there is anything else we could do about it. We surely want to do as little work as possible on the main thread at startup.

**Comment by adam1929** [comment]
Hi @mrublev we added this issue into our plans. We are going to change internal architecture to fully support app API as Async processes, but it leads to major changes.
For your case, please try to use SDK in background thread yourself for now. Thank you
