### ISSUE TITLE
Unable to change configuration

### ISSUE THREAD

**Issue by michals92** [exponea/exponea-ios-sdk#29]
We have specific problem with our iOS app in Notino. We need to change configuration and switch to different project during runtime. We have multiple languages in app, that we switch accordingly to country and we have different projects for each country. I found in Exponea SDK, that configuration is possible only once. Is there any way to change **projectToken** during runtime?

**Comment by michaela-dev** [comment]
Hi @michals92, thanks for your message. Yes, switching the project is available with calling anonymized, it's mentioned here in the documentation: https://gitlab.com/panaxeo/exponea/ios-sdk/-/blob/develop/Documentation/ANONYMIZE.md#project-settings-switch. You can pass Exponea project, you want to switch to, as a parameter. It anonymizes the user and starts tracking as if the app was just installed. Just note that all current customer identification (including cookie) will be permanently deleted.
