### ISSUE TITLE
AppStore upload failed

### ISSUE THREAD

**Issue by milanhorvatovic** [exponea/exponea-ios-sdk#33]
Hi, we faced a problem with uploading a new version of our application to the App Store with received errors:
- ITMS-90205
- ITMS-90206

After a short investigation in your latest release, I found the settings for ExponeaSDK target has 2 dependencies: 
- ExponeaSDKObjC
- ExponeaSDKShared

Both of those dependencies have an embed style as `Embed & Sign` that is the problem cause frameworks don't have allowed containing any nested bundles, which in that case are real frameworks.

Other than that, you should consider enabling the flag `BUILD_LIBRARY_FOR_DISTRIBUTION` to enable library evolution support for built frameworks.

**Comment by michaela-dev** [comment]
Hi, can you share (maybe screenshot) your targets and build settings? Mainly in part  "Embedded code contains swift code" + and "Framework search paths". It would be a big help. Thanks!

**Comment by milanhorvatovic** [comment]
Build settings for the project are:
- Embedded Content Contains Swift Code: NO (EMBEDDED_CONTENT_CONTAINS_SWIFT)
- Framework search paths: $(PROJECT_DIR)/ThirdPartyFrameworks/Exponea

To be honest, I don't think that the problem is in our project settings. We haven't had the problem with uploading binary to AppStore with embedded ExponeaSDK in our project until we updated to the latest v2.11.1 version. I checked your source code again and the problem is that commit [d3c9413](https://github.com/exponea/exponea-ios-sdk/commit/d3c9413209983219d89b25bd0c1af4d252c02ea4). The commit that you made define ExponeaSDKObjC and ExponeaSDKShared frameworks as not only dependencies, but also embedded them directly in ExponeaSDK archived binary (`Embed & Sign`).

We fixed our current situation by manual change in your project settings with simple change to Embed strategy from `Embed & Sign` to `Do Not Embed`.

**Comment by michaela-dev** [comment]
Great, thanks for the feedback!  We will fix this in the next release.

**Comment by milanhorvatovic** [comment]
I think the whole commit [d3c9413](https://github.com/exponea/exponea-ios-sdk/commit/d3c9413209983219d89b25bd0c1af4d252c02ea4) `fix/Include frameworks in SDK as required` could be removed, because it does nothing after all. Embed strategy `Do Not Embed` doesn't affect anything, am I wrong or do I miss something?

**Comment by michaela-dev** [comment]
Thanks again for noticing this, ExponeaSDKObjC and ExponeaSDKShared are not embedded anymore on version 2.11.2
