### ISSUE TITLE
Update code for latest Swift (5.3+) versions & address warnings

### ISSUE THREAD

**Issue by username0x0a** [exponea/exponea-ios-sdk#35]
As Swift has been evolving, some changes in the language alone (mainly around the 4.x/5.x version edges) lead to some of the conventions being deprecated.

At this moment with Xcode 13 (and AFAIK also previously with Xcode 12 cycle), a couple of warnings appears when building the library:

<img width="630" alt="Screenshot 2022-01-10 at 22 31 21" src="https://user-images.githubusercontent.com/5228484/149013823-9b77c58d-441e-4b02-a844-83257858e3a3.png">

This is a very minor change required, so addressing this should be a half-an-hour job in fact. 👍 Taking it practically, App Store currently requires Xcode 12 to be used to build any bundle deployed there, that means Swift 5.3 is effectively the oldest version supported. Your `Package.swift` file already states this, thus fixing this shouldn't really cause conflicts in any 3rd-party project. 👌

**Comment by michaela-dev** [comment]
Hi, thanks for noticing this 👍 . It's already fixed, the next iOS SDK release containing the fix should be out within this/next week.

**Comment by michaela-dev** [comment]
Fixed in 2.11.2 release
