### ISSUE TITLE
Exponea SDK is broken since 2.12.0

### ISSUE THREAD

**Issue by username0x0a** [exponea/exponea-ios-sdk#36]
Getting an error during configuration – complaining about database initialisation. Referenced in our project as a source Swift package.

My guess would be [this change](https://github.com/exponea/exponea-ios-sdk/blob/f3ade0a57537ad140f78a1a5cad3d67777cd69ca/ExponeaSDK/ExponeaSDK/Classes/Database/DatabaseManager.swift#L19) made in that release:

```swift
//        #if SWIFT_PACKAGE
//        let bundle = Bundle.module
//        #else
//
//        #endif
```

so that the proper `Bundle`, thus the database model file as well, can't be resolved properly.

That release seems to be pretty wild on its own, with `+14000` line diff, not really reviewed or tested properly, seems like.

**Comment by adam1929** [comment]
Thank you for detailed reporting. We were adding a new feature that required lot of changes to support Carthage, SPM and Cocoapods managers. This database handling has been changed due to 'obsolete' usage, but we will look at it definitely.

**Comment by adam1929** [comment]
@username0x0a  May I ask for some error message or anything?
This problem seems to be related with SPM. Which version XCode you have? It (probably) is runtime issue, which iOS version is affected? etc...
Thank you

**Comment by username0x0a** [comment]
The thrown error is `.unableToCreatePersistentContainer`, originating [here](https://github.com/exponea/exponea-ios-sdk/blob/8a04e65a638cef412078cdfe6a369bd231637913/ExponeaSDK/ExponeaSDK/Classes/Database/DatabaseManager.swift#L26).

As mentioned, very probably caused by invalid `Bundle` resolution causing the database model file not to be found.

Xcode 13.4.1, iOS 14+, integrated & built via SPM

**Comment by adam1929** [comment]
@username0x0a Thank you, we found a problem in SDK. Yes indeed, we comment out that part of code for invalid reason, this version of SDK is incopatible with SPM usage. We'll revert this change asap, in next iOS SDK release
