### ISSUE TITLE
Support Xcode 14, iOS 16

### ISSUE THREAD

**Issue by DurnevY** [exponea/exponea-ios-sdk#37]
Hi, pls fix this for new xcode, thx.
'isElementFullscreenEnabled' is only available in iOS 15.4 or newer
![Снимок экрана 2022-09-05 в 12 24 41](https://user-images.githubusercontent.com/101252604/188416044-798fb083-16f7-4010-8b87-d44c8cabf24d.png)

**Comment by adam1929** [comment]
Hi @DurnevY 
Unfortunately XCode14 is still in Beta, we cannot support it at 100%
This issue is unfortunate, because XCode13.4.1 with Swift5.6 is saying that this field is available from 15.0, but XCode14+Swift5.7 are saying from 15.4, same as AppleDocs :-O
We'll investigate it deeply, which info is correct

**Comment by adam1929** [comment]
Hi @DurnevY 
We have to stay on "stable" state of XCode13, where the property is marked as `@available(iOS 15.0, *)`
I hope for XCode14 to be released soon in stable state, not in Beta. Apple may changed their decision, please wait until that.
This property is part of security setup, we should not make it vulnerable for iOS 15.0->15.3 devices (by changing that if statement to fit XCode14 config)
Thank you for understanding.

**Comment by MatyasKriz** [comment]
FYI, Xcode 14 was released yesterday, so this issue is now more relevant than ever. @adam1929

**Comment by sgrgrsn** [comment]
@adam1929 As you can see above, @olejnjak already made a fix for it. Could we please have this fix released so Exponea is no longer blocking us from upgrading to Xcode 14?

Thanks!

**Comment by adam1929** [comment]
Hi, we are going to fix this IF for XCode 14. Thank you all for patience and for understanding of our "only stable XCode" support statement. Fix from @olejnjak is the best one solution, TBH we are using. Thank you

**Comment by olejnjak** [comment]
Well, the RC (which is out for almost 2 weeks) should probably be considered "stable" , therefore this issue could have been already resolved 🤷‍♂️

**Comment by adam1929** [comment]
Fix delivered in latest release https://github.com/exponea/exponea-ios-sdk/releases/tag/2.12.3
