### ISSUE TITLE
BC-breaking use of `isElementFullscreenEnabled`

### ISSUE THREAD

**Issue by username0x0a** [exponea/exponea-ios-sdk#38]
In Xcode 13.4.1/iOS 15.5 SDK, `WKPreferences.isElementFullscreenEnabled` is defined as `API_AVAILABLE(macos(12.0), ios(15.0))`. However in Xcode 14/iOS 16 SDK, this has been changed to `API_AVAILABLE(macos(12.3), ios(15.4))` – this can be seen both in the reference for the property in Xcode 14 as well as on [Apple Documentation website](https://developer.apple.com/documentation/webkit/wkpreferences/3917769-elementfullscreenenabled/). Apple screwed it here, but they probably have reasons to rise that requirement in the end.

Because of [this line](https://github.com/exponea/exponea-ios-sdk/blob/8a04e65a638cef412078cdfe6a369bd231637913/ExponeaSDK/ExponeaSDK/Classes/InAppMessages/View/InAppMessageWebView.swift#L92):

```swift
        if #available(iOS 15.0, *) {
            preferences.isElementFullscreenEnabled = false
        }
```

Exponea package fails to compile in Xcode 14.

I'd suggest to simply rise the `if #available` condition to `15.4`, just so it can be compiled now with Xcode 13.4.1 as well as later on with Xcode 14.

Now I can see I'm duplicating #37 😅 but doing it this way would allow building Exponea everywhere, with no public API being broken as this mentioned code is internal. 👍

Xcode 14 is also in RC so there's not really a high probability this will change.

**Comment by adam1929** [comment]
Fix delivered in latest release https://github.com/exponea/exponea-ios-sdk/releases/tag/2.12.3
