### ISSUE TITLE
Fatal on Push Notification Opening

### ISSUE THREAD

**Issue by jackjpark** [exponea/exponea-ios-sdk#4]
I have encountered a further Issue when sending a push notification, when user taps the notification, app opens and then fatal error occurs in SDK:

Fatal on this line of the `PushNotificationManager+NSObject` class:

` guard let originalMethod = class_getInstanceMethod(type(of: self), selector),
            let swizzle = Swizzler.swizzles[originalMethod] else {
                return
        }`

also appears to call this func over and over in the stack trace

`curriedImplementation(self, selector, center, response, completionHandler)`

Is there any additional config required in the app when NOT using rich push notifications? As the demo app implies not but why is this crash occurring if thats the case? Appreciate guidance on this

**Comment by jackjpark** [comment]
I have reverted to manual push notification handling to get around these swizzling crashes but there is a lack of documentation on how to support the webview and deeplink exponea push notifications when not using the automatic tracking... 

Can you either provide guidance on handling this, or offer insight as to why the swizzling is causing so many fatals? thanks

**Comment by nickskull** [comment]
Hi @jackjpark, can you please tell me how have you setup push notifications in your project? Which app delegate or UNUserNotifications delegate methods have you overridden?

**Comment by jackjpark** [comment]
> Hi @jackjpark, can you please tell me how have you setup push notifications in your project? Which app delegate or UNUserNotifications delegate methods have you overridden?

Yep sure, so the ApplicationController inits a `UserNotificationCenter` on app start, which conforms to `UNUserNotificationCenterDelegate` and takes `UNUserNotificationCenter.current()` injection on init where it sets its delegate to our `UserNotificationCenter` class

**Comment by nickskull** [comment]
@jackjpark Ok, thanks. Is this happening before or after initialising Exponea?

**Comment by jackjpark** [comment]
> @jackjpark Ok, thanks. Is this happening before or after initialising Exponea?

We always init exponea on startup now so its always running (got rid of the lazy init when working on the previous issue), so when receiving a push, exponea would always have been initialised. Ill crash the app and provide a log in a minute as it takes some setup

**Comment by jackjpark** [comment]
> > @jackjpark Ok, thanks. Is this happening before or after initialising Exponea?
> 
> We always init exponea on startup now so its always running (got rid of the lazy init when working on the previous issue), so when receiving a push, exponea would always have been initialised. Ill crash the app and provide a log in a minute as it takes some setup

All im able to see if the fatal on:
`guard let originalMethod = class_getInstanceMethod(type(of: self), selector),
            let swizzle = Swizzler.swizzles[originalMethod] else {
                return
        }`
on 
`func userNotificationCenter(_ center: UNUserNotificationCenter,
                                      newDidReceive response: UNNotificationResponse,
                                      withCompletionHandler completionHandler: @escaping () -> Void)`

Im unable to see any device logs to share unless you can provide guidance as to where I can location further useful data?

**Comment by nickskull** [comment]
@jackjpark Thank you. It seems that the infinite loop is hiding the original stack trace, so I can't read out much out of these logs. When the push happens does any of your delegate methods get called? Or does it instantly go into the infinite loop? Also, was the app in the background or completely killed when this happened?

I've tried experimenting in the example project and replicating the scenario you describe you have in your app and I can't make it run into the loop. Are you using any other SDKs or libraries for push, or are you doing swizzling in your app?

**Comment by jackjpark** [comment]
> @jackjpark Thank you. It seems that the infinite loop is hiding the original stack trace, so I can't read out much out of these logs. When the push happens does any of your delegate methods get called? Or does it instantly go into the infinite loop? Also, was the app in the background or completely killed when this happened?
> 
> I've tried experimenting in the example project and replicating the scenario you describe you have in your app and I can't make it run into the loop. Are you using any other SDKs or libraries for push, or are you doing swizzling in your app?

I dont get calls on my delegate methods before the loop crash (though when i switched to manual integration i was also unable to get an exponea push notification to trigger any delegates), I am using Mixpanel and FIrebase which i think have functions around notifications but we havent actively enabled them, just import the SDK's for other uses, we dont swizzle ourselves

**Comment by jackjpark** [comment]
@nickskull Hi, was there any further steps I can take on this? im happy to use manual integration instead if automatic is a dead end, however theres no documentation on handling exponeas push notifications manually within the app?

**Comment by nickskull** [comment]
Hi @jackjpark, I apologize for the delay in communication. We've really tried testing out all the scenarios including implementing the other dependencies you mentioned and can't seem to reproduce the issue. The only thing I can think of is if you could try and create and empty project and see if you're able to reproduce it there.

Regarding manual setup - your best course of action is to check the JSON that's at the end of [this guide](https://github.com/exponea/exponea-ios-sdk/blob/develop/Documentation/PUSH.md) and the source code of the Exponea's notification service and content extensions to see how we handle the rich push.

**Comment by jackjpark** [comment]
Hi @nickskull we have resolved this now, the issue if we handled the delegate methods in an extension of a protocol and the swizzle cant handle that sort of setup, so it would crash, restoring to a more traditional setup resolved the crash

**Comment by nickskull** [comment]
Hi @jackjpark, thank you for the information! I'll make sure to add this to the setup guide for future reference if anyone runs into a similar issue. I'm glad you were able to resolve this.
