### ISSUE TITLE
Rich push notifications

### ISSUE THREAD

**Issue by DamyanPOQ** [exponea/exponea-ios-sdk#44]
Hello, 
I am using Exponea SDK 2.14.0.
iOS deployment targets iOS 14.0 for both extensions and the app.
I am following this guide: 
https://github.com/exponea/exponea-ios-sdk/blob/develop/Documentation/Guide/PUSH_QUICKSTART.md

Notifications are working fine but the Rich push notifications with images and buttons do not work properly.
I receive the notification but once I long press it nothing is happening.
Please review the Documentation for some missing configuration details.

**Comment by adam1929** [comment]
Hi @DamyanPOQ did you fix issue meanwhile? If not, please report issue with QA, we would love to help you with it (with some questions of course 😃  )
