### ISSUE TITLE
Delivered Event not triggered for users who update their app to one which integrates Bloomreach

### ISSUE THREAD

**Issue by termorrell** [exponea/exponea-ios-sdk#50]
It may be worth updating documentation to clarify how users with existing push tokens should configure the service extension.

We configured our push implementation using the following documentation:
- https://github.com/exponea/exponea-ios-sdk/blob/develop/Documentation/PUSH.md#tracking-delivered-notifications
- https://github.com/exponea/exponea-ios-sdk/blob/develop/Documentation/Guide/PUSH_QUICKSTART.md

We were migrating from an existing provider to Bloomreach so already had push tokens and consent for many of our users. After importing the tokens to Bloomreach we observed that we weren't seeing 'Delivered' events for many of our users.

The documentation describes calling `.configure` in `didFinishLaunchingWithOptions`. While this will work for users who open the app, any push notifications that trigger the service extension before the app is opened will not be able to track 'Delivered'.

1. Is it safe to call `.configure` and `.identify` multiple times with the same parameters, in the service extension and main app?
2. You may want to consider updating the documentation to reflect the need to call `.configure` and `.identify` in the service extension to handle the case where a user is backfilling with existing push tokens and app opens are infrequent.

**Comment by Ankmara** [comment]
Hi, thank you for contacting us. Delivered events are saved (user defaults) and called after SDK init - are you sure that you have correct app group? Thank you for response
