### ISSUE TITLE
Could not find module 'ExponeaSDK' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator,

### ISSUE THREAD

**Issue by litephilip** [exponea/exponea-ios-sdk#54]
Can't start build process due to this problem:
Could not find module 'ExponeaSDK' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator at: /Users/name/Library/Developer/Xcode/DerivedData/<project-name>/Index.noindex/Build/Products/Debug-iphonesimulator/ExponeaSDK.swiftmodule

Tried to update dependency to pod "ExponeaSDK", "~> 2.20.0", and changed all necessary config in my Xcode project. 
Any advice to solve this problem?

Xcode version: 15.0.1
Computer: Mac M1

**Comment by xcibik00** [comment]
Hi @litephilip, we also updated it in 2.21.0
