### ISSUE TITLE
BadDeviceToken on eventlogs

### ISSUE THREAD

**Issue by litephilip** [exponea/exponea-ios-sdk#56]
I am encountering a persistent issue when attempting to send push notifications to my iOS device. Every time I try to send a notification, I receive a response with the error comment: "BadDeviceToken" in my event logs.

I have thoroughly checked and confirmed that the device tokens used are correct. I've tried using both production and development (test) environment tokens, ensuring they are properly encoded. Despite these efforts, the issue remains unresolved.

Could you please provide guidance on what might be causing this "BadDeviceToken" error and how to resolve it? Is there a specific format or configuration that I might be missing,

**Comment by Ankmara** [comment]
Hi, could you send us your implementation please? Thank you

**Comment by rameshmicapg** [comment]
Hi @Ankmara i also facing same issue.

**Comment by Ankmara** [comment]
Hi, is this issue still relevant? Did you use method `Exponea.shared.handlePushNotificationToken(deviceToken: deviceToken)`?
