### ISSUE TITLE
how to convert dictionary to [String : any JSONConvertible]

### ISSUE THREAD

**Issue by rameshmicapg** [exponea/exponea-ios-sdk#57]
Cannot convert value of type '[String : Any]' to expected argument type '[String : any JSONConvertible]'
any one help me

**Comment by rameshmicapg** [comment]
Exponea.shared.trackPayment(
              properties: trackingDataSource,
              timestamp: nil
            )

**Comment by rameshmicapg** [comment]
Cannot convert value of type '[String : Any]' to expected argument type '[String : any JSONConvertible]'

**Comment by Ankmara** [comment]
Hi thank you - can I see implementation of "trackingDataSource"?

**Comment by rameshmicapg** [comment]
YES

**Comment by Ankmara** [comment]
Hi thank you for response. Where can I find the code?
