### ISSUE TITLE
Request self-check push & Test Notification not working

### ISSUE THREAD

**Issue by krzysztofs4d** [exponea/exponea-ios-sdk#61]
Hi, 

I've tried to configure push notification but i'm not able to send test push via website and SDK fails at **Request self-check push** step.

![IMG_4322](https://github.com/exponea/exponea-ios-sdk/assets/91970311/dbc835c0-1ef6-4025-a351-af5c6a202178)

When i try to send test push message from website to single / test customer (with **apple_push_notification_id** set up) I get **400 Bad Request** error popup. 

APNS configuration is set up properly in Project Settings and test customer is having both **apple_push_notification_id** and **apple_push_notification_authorized** properties. 

On iOS App it fails at last step. I've tried look at request iOS SDK is making and **url, project_id, Authorization** and **httpBody** looks ok but the response is
`BadRequest: The browser (or proxy) sent a request that this server could not understand.`

Im using public API with very limited access (email, apple_push_notification_id, apple_push_notification_authorized). 

Is there anything that i'm missing? I run through documentation for both iOS and Android and i can't find anything that could be wrong. I suspect it might be because of public API restrictions but i couldn't find what else should be enabled to be able to send push notifications.

**Comment by xcibik00** [comment]
Hi @krzysztofs4d , I would like to ask you if you can give us information about how you solved the given situation? Best through [official support](https://documentation.bloomreach.com/engagement/docs/engagement-support#contacting-the-support) with client name and project ID
Thanks!

**Comment by krzysztofs4d** [comment]
Hi @xcibik00, I had app signed using Development certificates and Exponea configuration was using Production API.
