### ISSUE TITLE
Pointer being freed was not allocated

### ISSUE THREAD

**Issue by sergei-mikhailovskii-idf** [exponea/exponea-ios-sdk#62]
Hi, after the update of the SDK to the 2.23.0 version we faced the following crash in production. Here's the stacktrace. Can it be fixed? Feel free to contact me for any support you need, thanks!

[6ea2884793a64be4a2b1de193a56fdb8-symbolicated.txt](https://github.com/exponea/exponea-ios-sdk/files/14635347/6ea2884793a64be4a2b1de193a56fdb8-symbolicated.txt)

**Comment by Ankmara** [comment]
Hi, thank you for report. When the app crash? After launch, or after use InAppMessage for example? Thank you

**Comment by sergei-mikhailovskii-idf** [comment]
@Ankmara hi! it's hard to say since this case happened at prod and we don't have enough logs in this case. but as I understand it happened when we tried to show the in-app message right after the launch

**Comment by Ankmara** [comment]
Hi, we will release (today) new version with fix of this issue and some new features. Could you test it and let me know if everything is ok, please?

**Comment by xcibik00** [comment]
Hi @sergei-mikhailovskii-idf - 2.25.0 is already available, please let us know if it fix your problem
Thanks!
