### ISSUE TITLE
Adding privacy manifest to Package.swift

### ISSUE THREAD

**Issue by willinDrive** [exponea/exponea-ios-sdk#64]
Please add PrivacyManifest to Package.swift as resource. Because 2.25 version doesn't contain it in archived bundle

Example 
* https://github.com/Alamofire/Alamofire/blob/master/Package.swift#L40
* https://github.com/airbnb/lottie-ios/blob/master/Package.swift#L22

![image](https://github.com/exponea/exponea-ios-sdk/assets/120020052/68778a0e-7b76-414a-b489-8566adad500a)

![image](https://github.com/exponea/exponea-ios-sdk/assets/120020052/a3ac69db-7e25-44dd-8aea-7eb85486dbf2)

**Comment by xcibik00** [comment]
Hi @willinDrive , thank you for pointing to it and sorry for the issue, we already updated it in 2.25.1, can you please check and let us know if its working for you just fine?
Thanks!
