### ISSUE TITLE
InAppContentBlock in demo app is not showing

### ISSUE THREAD

**Issue by HannaDigis** [exponea/exponea-ios-sdk#65]
Installed demo app via link from original documentation
https://documentation.bloomreach.com/engagement/docs/ios-sdk-example-app
Xcode Version 15.3 (15E204a)
Min target: 12.0
Destination: iPhone
Testing devices: real device iPhone 11, simulator iPhone 15 Pro, iPhone 15 Pro Max

When running app, on Authentication view entered my project token, API token, and API base URL
Also tried with API Base URL https://api.exponea.com/ (default option)
Went into tab for InAppContentBlocksViewController
I was able to see table view only with numbers, but there were no content blocks
Screenshot and logs in zip files are attached 

PS: I have noticed that in documentation there is a screenshot of several view controllers including InAppContent, but content blocks are missed there too. 
screenshot from documentation
<img width="273" alt="Screenshot 2024-05-01 at 4 49 20 PM" src="https://github.com/exponea/exponea-ios-sdk/assets/137176904/b831d270-1967-4ae0-a826-58b559193ec1">

screenshot from my test
<img width="349" alt="Screenshot 2024-05-01 at 4 45 55 PM" src="https://github.com/exponea/exponea-ios-sdk/assets/137176904/4dcb5cf1-da3d-443a-a134-b71ca1eed194">

log file
[demo app logs.zip](https://github.com/exponea/exponea-ios-sdk/files/15182257/demo.app.logs.zip)

**Comment by Ankmara** [comment]
Hi, thank you for report. 
1 - do you have active campaign?
2 - jf yes, please, wait for self check alert on the first screen after login. Then go to content block page and you will see your messages.

**Comment by HannaDigis** [comment]
Hello
1- yes, we do. It works on Android, but not on iOS. That's why I was trying to check CB in demo app
2- I can see self check alert. As I understand, self check push is not necessary for CB feature. Still, after getting this alert and going to content block page, I'm not able to see any CB
<img width="349" alt="Screenshot 2024-05-14 at 8 44 42 AM" src="https://github.com/exponea/exponea-ios-sdk/assets/137176904/876c98c4-00a5-4ce1-9980-ca5c01eb89f2">

**Comment by Ankmara** [comment]
Hi,

could send us your logs via support  form, please?

Thank you

**Comment by HannaDigis** [comment]
Could you please provide an instruction how to do it?

**Comment by Ankmara** [comment]
Please follow these steps: https://documentation.bloomreach.com/engagement/docs/ios-sdk-in-app-content-blocks#troubleshooting

Thank you.

**Comment by xcibik00** [comment]
Hi @HannaDigis , 
Regarding to "I can see self check alert. As I understand, self check push is not necessary for CB feature" -> yes you are right, but this is the behaviour of our example app, check is not necessary for CB feature, but its a signal and check/last step if all is initialised OK, after that you should see the CBs in that app section, if not it can be a problem with campaign configuration etc. or placeholder mapping -> to tell more we need to see the full log
I recommend to use (We do not know which SDK version you are using) to use 2.25.3+ SDK version with extended verbose logging for In-app content blocks
Thanks!
