### ISSUE TITLE
after run pod file. they are showing issue 

### ISSUE THREAD

**Issue by rameshmicapg** [exponea/exponea-ios-sdk#67]
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.
1. 'shared' has been explicitly marked unavailable here (UIKit.UIApplication)

these error are showing many class so please let me know this issue.
<img width="677" alt="Screenshot 2024-05-06 at 7 20 46 PM" src="https://github.com/exponea/exponea-ios-sdk/assets/96046143/9deaec09-537f-4a96-87cf-3c69437a4cb6">

**Comment by adam1929** [comment]
Hi @rameshmicapg thank you for reporting. I was not able to understand why this error is shown to you. We are using UIApplication.shared in Example app and SDK for long time without this problem.
Could you please describe your setup more detailed? For example XCode version, supported destination (Xcode>Target>General), swift version. More info = higher chance to detect problem. Thank you.

**Comment by adam1929** [comment]
Or you are using SDK in extension probably? If so, please try to describe your usage for that. SDK should be used in main app module and Notification extensions has to use ExponeaSDK-Notifications.
App extensions has to be lightweight as possible.
Thank you for clarification.
