### ISSUE TITLE
exponea-ios-sdk - generates incorrect NSPrivacyAccessedAPICategoryUserDefaults values in react-native projects

### ISSUE THREAD

**Issue by gdhillon-pbl** [exponea/exponea-ios-sdk#69]
### Title:

exponea-ios-sdk generates incorrect NSPrivacyAccessedAPICategoryUserDefaults value `“C617.1”` in react-native projects

### Description:

When using exponea-ios-sdk within a react-native project, the auto-generated PrivacyInfo.xcprivacy file contains incorrect value(`“C617.1”`) for the NSPrivacyAccessedAPICategoryUserDefaults category. This is due to erroneous values within the exponea-ios-sdk itself.

The specific files containing the incorrect values are:

- https://github.com/exponea/exponea-ios-sdk/blob/main/ExponeaSDK/ExponeaSDK/Supporting%20Files/PrivacyInfo.xcprivacy
- https://github.com/exponea/exponea-ios-sdk/blob/main/ExponeaSDK/ExponeaSDK-Notifications/Supporting%20Files/PrivacyInfo.xcprivacy 

**This misreporting causes an "Invalid Binary" issue in App Store Connect, preventing successful submission.**

### Steps to Reproduce:

1. Integrate [exponea-react-native-sdk](https://github.com/exponea/exponea-react-native-sdk) and exponea-ios-sdk into a react-native project.
2. Build the project, triggering the automatic generation of PrivacyInfo.xcprivacy.
3. Inspect the generated PrivacyInfo.xcprivacy file and observe the incorrect values under NSPrivacyAccessedAPICategoryUserDefaults.

<img width="699" alt="image" src="https://github.com/exponea/exponea-ios-sdk/assets/48697687/506ee7e0-4d3e-4258-a143-874eeabd7f8c">

### Expected Behavior:

The generated PrivacyInfo.xcprivacy should reflect accurate usage of NSUserDefaults as per Apple's guidelines: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api. 

### Failure from app store connect 

_ITMS-91055: Invalid API reason declaration - The PrivacyInfo.xcprivacy for the “APP NAME” file contains “C617.1” as the value for a NSPrivacyAccessedAPITypeReasons key instead of a valid reason code for using an API in the NSPrivacyAccessedAPICategoryUserDefaults category. Values for NSPrivacyAccessedAPITypeReasons keys in any privacy manifest must be valid reason codes for the corresponding API category. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api._

**Comment by Ankmara** [comment]
Hi, thank you for report. Will be fixed in next release.

**Comment by xcibik00** [comment]
Hi @gdhillon-pbl is fixed in 2.26.2 version of iOS SDK
