### ISSUE TITLE
Privacy manifest issues

### ISSUE THREAD

**Issue by AmeliaIsCoding** [exponea/exponea-ios-sdk#77]
App Store Connect raised the following warnings to do with the privacy manifest file. Could these please be fixed?

ITMS-91106: Invalid API reason declaration - The PrivacyInfo.xcprivacy file at the “Frameworks/ExponeaSDK.framework/ExponeaSDK.bundle/PrivacyInfo.xcprivacy” path contains “C617.1” as the value for a NSPrivacyAccessedAPITypeReasons key instead of a valid reason code for using an API in the NSPrivacyAccessedAPICategoryUserDefaults category. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. Values for NSPrivacyAccessedAPITypeReasons keys in any privacy manifest must be valid reason codes for the corresponding API category. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: [Adding a privacy manifest to your app or third-party SDK | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk)  and [Describing use of required reason API | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) . 

ITMS-91107: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/ExponeaSDK.framework/ExponeaSDK.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. Keys and values in any privacy manifest must be valid. For more details, visit: [Privacy manifest files | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)  and [Adding a privacy manifest to your app or third-party SDK | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk) .

**Comment by AmeliaIsCoding** [comment]
We are using ExponeaSDK 2.28.0

**Comment by xcibik00** [comment]
And are you sure that the warnings are from the version using Exponea iOS SDK (or notification) version 2.26.2 +?
Because as you can see in the 2.28.0 (from 2.26.2+) its updated/fixed:

* https://github.com/exponea/exponea-ios-sdk/blob/189c7c7c3ae572e91b9398bd2289cdb205d9ac88/ExponeaSDK/ExponeaSDK-Notifications/Supporting%20Files/PrivacyInfo.xcprivacy
* https://github.com/exponea/exponea-ios-sdk/blob/189c7c7c3ae572e91b9398bd2289cdb205d9ac88/ExponeaSDK/ExponeaSDK/Supporting%20Files/PrivacyInfo.xcprivacy

**Comment by AmeliaIsCoding** [comment]
I am sure, and I believe these two issues are different from that fixed in 2.26.2. 

For example the warning says "NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty."

This would be my suggested fix, however I'm completely unfamiliar with these .xcprivacy files, so I'm not certain, but I compared to .xcprivacy files for other pods.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTracking</key>
	<false/>
	<key>NSPrivacyTrackingDomains</key>
    <array>
    </array>
	<key>NSPrivacyAccessedAPITypes</key>
	<array>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>C617.1</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<string>NSPrivacyAccessedAPICategoryUserDefaults</string>
			<key>NSPrivacyAccessedAPIType</key>
			<array>
            	<string>CA92.1</string>
            </array>
		</dict>
	</array>
.........
```

**Comment by AmeliaIsCoding** [comment]
Hello, just wondering if you saw the above / if you are looking into this? :)

**Comment by Ankmara** [comment]
Hi, we can't add some domains in manifest file, because we don't know who add which. So you need to add NSPrivacyTracking as true on your side if you have some domains in your app.
