### ISSUE TITLE
`Exponea.shared.handlePushNotificationOpened*` with universal link not working with `SwiftUI.App` root

### ISSUE THREAD

**Issue by sjavora** [exponea/exponea-ios-sdk#78]
When using the new(ish) SwiftUI app root, even with `@UIApplicationDelegateAdaptor`, it's not possible to access that instance using `UIApplication.shared.delegate`. SwiftUI assigns its own type (`SwiftUI.AppDelegate`) and resubmits _some_ callbacks to modifiers like `.onOpenURL`. This breaks opening universal links sent to `Exponea.shared.handlePushNotificationOpened*` methods, as those eventually end up in Exponea's `UrlOpener.openUniversalLink`, which tries to trigger `application(_:continue:restorationHandler:)` on `UIApplication.shared.delegate`. As explained above, this is not the appDelegate instance from `@UIApplicationDelegateAdaptor`, but `SwiftUI.AppDelegate`. The method returns `false`, leading to the fallback behavior of `UrlOpener.openURLSchemeDeeplink`. `application.open(_:options:completionHandler:)` doesn't route universal links to the app and opens the browser instead.

I have found that while the scene delegate also gets replaced (with `SwiftUI.SceneDelegate`), a call to that will forward user activity calls to SwiftUI's `.onContinueUserActivity`:

```swift
let scene = UIApplication.shared.connectedScenes.compactMap({ $0 as? UIWindowScene }).first!
let activity = NSUserActivity(activityType: NSUserActivityTypeBrowsingWeb)
activity.webpageURL = ...
scene.delegate?.scene?(scene, continue: activity)
```

So I suggest this be added to `UrlOpener` as another thing to try before falling back to `application.open(_:options:completionHandler:)`.

**Comment by sjavora** [comment]
This is what I'm using in the meantime: https://github.com/kiwicom/exponea-ios-sdk-swiftui/commit/7e2776eb5f11eaa60033405521fcf3d5921082c7

**Comment by Ankmara** [comment]
Hi, thank you - we will check it. Your suggestion looks fine at first look.

**Comment by sjavora** [comment]
Hey, @Ankmara why was this closed? The current version of the SDK still exhibits this behavior.

**Comment by xcibik00** [comment]
Hi @sjavora , you are right that this is not added to SDK. We already checked it also with the PO and considered that there is no priority on it right now, we added it as a backlog item and since It is more like adding support for that rather than bug/issue in SDK we already closed it here..
But if there will be any update on it, we will let you know.
If there is a blocker for you or high priority item, please contact your Bloomreach CSM or official support to.
Thanks
