### ISSUE TITLE
Version 3.0.0 give compilation error

### ISSUE THREAD

**Issue by emadhegab** [exponea/exponea-ios-sdk#79]
I installed version 3.0.0 via SPM , and i suddenly got error in `ManualSegmentsCacheDTO` Cannot find 'Date' in scope  i think due to that Foundation is not imported in that module  . 

<img width="1168" alt="image" src="https://github.com/user-attachments/assets/1c946cf7-db3d-48b8-9130-013b41665835">

**Comment by miquel-cooltra** [comment]
We are experiencing the same error
