### ISSUE TITLE
Tapping a push notification with deeplink triggers deeplink multiple times

### ISSUE THREAD

**Issue by jackjpark** [exponea/exponea-ios-sdk#8]
I am sending a deeplink to my app via exponeas push notifications, when tapped once, the app will open and handle the link, however it will execute the delegate method several times, leading to a view being presented 3-4 times rather than once.

Executing this code via tapping the deeplink from the notes app rather than an exponea push will execute only once as expected, therefore we propose that perhaps exponea SDK is calling actions more than once when it receives push notifications

**Comment by jackjpark** [comment]
@Igi4 Hi, any updates on this?

**Comment by Igi4** [comment]
@jackjpark Hi, we tried to reproduce it but we were unlucky so far. Could you please provide more information about your particular setup?

Is it happening all the time or spontaneously?

We are taking a more thorough look this week so any additional information might help.

**Comment by jackjpark** [comment]
Hi,

So its the PushNotificationManagerDelegate class, method pushNotificationOpened

This method is called multiple times when a user taps a push notification which contains a deeplink, leading to the code we wrote inside this delegate method being run multiple times and causing multiple navigations on top of each other

Im uncertain why your SDK calls this method several times but it would seem to not be possible for it to be related to our code as its an interception from the Exponea SDK when opening the push and then its own delegate method call thats repeating?

**Comment by Igi4** [comment]
@jackjpark We have some new information. The Exponea SDK hooks the delegate method with swizzling to automatically call the delegate without any additional setup. It seems that this mechanism requires a little bit more tinkering to make it work correctly.

Do you have any other SDKs integrated in the app? The most probable cause is that there are multiple SDKs using this same approach and the delegate in the Exponea's SDK ends up being registred more than once. If you have more SDKs in the app, could you please try intitalizing the Exponea SDK as the last one? It might help to temporarily fix it until we update the SDK.

**Comment by jackjpark** [comment]
Hi @Igi4 we are using Zendesk Chat SDK, Mixpanel, Firebase and Appsflyer. I have moved Exponea to init last as recommended but would appreciate an ETA on a fix as this is quite detrimental to our production use of the SDK and our end users experience

**Comment by Igi4** [comment]
@jackjpark Hey, sure. We have the fix almost ready and it will be part of the next release (2.5.0) which is scheduled to be released on Nov 25 if everything goes well.

Has moving the SDK init to the last position helped in any way?

**Comment by jackjpark** [comment]
Hi

We are yet to release the change to see its result with our users, Thanks for the deadline on the fix as we can work this into our next release 

Jack

**Comment by Igi4** [comment]
Sure, no problem. I'll let you know as soon as the new version is deployed.

**Comment by Igi4** [comment]
Hey @jackjpark , the new version is out and it shouldn't trigger the deeplink multiple times anymore. Please let me know if it helped :)
