### ISSUE TITLE
InAppMessageWebView - layout modifications from bg thread

### ISSUE THREAD

**Issue by olejnjak** [exponea/exponea-ios-sdk#82]
Hi, 

in our app I am getting crashes in InAppMessageView that tries to modify layout from background thread ([stack trace attached](https://github.com/user-attachments/files/18006830/cz.voyo_issue_24a57db13ad1627452a74383f76f648e_crash_session_d2cfd8e253ec4b53bc0bdbf6da1c882e_DNE_8_v2_stacktrace.txt), [another one](https://github.com/user-attachments/files/18006925/cz.voyo_issue_0cac42106bff078f94e11c514da0b9fc_crash_session_0553c92e02b44a7db322279e4b779911_DNE_2_v2_stacktrace.txt)).

The message in Crashlytics says
> NSInternalInconsistencyException
> Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.

The app uses ExponeaSDK 3.0.1 installed by Carthage.

Would be great if this got fixed.

Thanks.

**Comment by Ankmara** [comment]
Hi, thank you for report. Contant us via official support please and provide part of your implementation etc. I checked it and IPMView is calling only from main thread. Thank you.
