### ISSUE TITLE
Apple Push Notification Service Server Certificate Update

### ISSUE THREAD

**Issue by sergei-mikhailovskii-idf** [exponea/exponea-ios-sdk#83]
Hi, we received the following email

> Hello, 
> 
> As we announced in October, the Certification Authority (CA) for Apple Push Notification service (APNs) is changing. APNs will update the server certificates in sandbox on January 20, 2025, and in production on February 24, 2025. To continue using APNs without interruption, you’ll need to update your application’s Trust Store to include the new server certificate: SHA-2 Root : USERTrust RSA Certification Authority certificate. 
> 
> To ensure a smooth transition and avoid push notification delivery failures, please make sure that both old and new server certificates are included in the Trust Store before the cut-off date for each of your application servers that connect to sandbox and production. At this time, you don’t need to update the APNs SSL provider certificates issued to you by Apple. 

from my point of view it looks like the change that will be done at the Exponea-Firebase servers integration but maybe there are some changes required from the side of the SDK users? Thanks

**Comment by Ankmara** [comment]
Hi, thank you for info. We will handle it.
