### ISSUE TITLE
Exponea schemes pollute Xcode via SPM

### ISSUE THREAD

**Issue by joshuapoq** [exponea/exponea-ios-sdk#84]
When depending on Exponea the [schemes here](https://github.com/exponea/exponea-ios-sdk/tree/main/.swiftpm/xcode/xcshareddata/xcschemes) are loaded into Xcode whenever the SPM dependencies change.

This pollutes Xcode when switching schemes which generally adds some annoyance and pain on a fairly regular basis. See [this discussion for more information](https://forums.developer.apple.com/forums/thread/716024) as this could be an Apple oversight or perhaps it's intended behaviour.

If possible, to fix you could you move the schemes into the workspace and target that for any CI?

**Comment by Ankmara** [comment]
Hi, thank you for report. Please, use our official support and provide some video/screenshot where is exactly the issue. I tried few apps with our SDK via SPM and everything looks normal - no schemes are loaded etc. Thank you.
